index:
    path: /
    defaults: { _controller: 'App\Controller\GraphQLController::index' }

# first, run composer req annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation
